# Generated by Django 5.2.6 on 2025-09-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cartaodecredito_conta_despesa_cartao_despesa_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='id_compra_parcelada',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='despesa',
            name='parcela_atual',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='despesa',
            name='parcelada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='despesa',
            name='parcelas_totais',
            field=models.IntegerField(default=1),
        ),
    ]
