# Generated by Django 5.2.6 on 2025-09-22 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_despesa_id_compra_parcelada_despesa_parcela_atual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categoriareceita')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.conta')),
            ],
        ),
    ]
