# Generated by Django 5.2.6 on 2025-09-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_categoriareceita_receita'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor_objetivo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_atual', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('data_limite', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
