# Generated by Django 5.2.6 on 2025-09-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_metafinanceira'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='id_recorrencia',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='despesa',
            name='recorrente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receita',
            name='id_recorrencia',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='recorrente',
            field=models.BooleanField(default=False),
        ),
    ]
