# Generated by Django 5.2.6 on 2025-09-23 12:06

from django.db import migrations

def criar_perfis_faltantes(apps, schema_editor):
    """
    Cria um Perfil para cada Usuário que ainda não tem um.
    """
    User = apps.get_model('auth', 'User')
    Perfil = apps.get_model('core', 'Perfil')
    
    # Pega todos os usuários que não têm um perfil associado
    usuarios_sem_perfil = User.objects.filter(perfil__isnull=True)
    
    # Cria um perfil para cada um deles
    for user in usuarios_sem_perfil:
        Perfil.objects.create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_familia_perfil'), # MUITO IMPORTANTE: Mude o 'X' para o número da sua migração anterior
    ]

    operations = [
        migrations.RunPython(criar_perfis_faltantes),
    ]