# Generated by Django 5.2.6 on 2025-09-23 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_criar_perfis_para_usuarios_existentes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartaodecredito',
            name='user',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='user',
        ),
        migrations.RemoveField(
            model_name='categoriareceita',
            name='user',
        ),
        migrations.RemoveField(
            model_name='conta',
            name='user',
        ),
        migrations.RemoveField(
            model_name='metafinanceira',
            name='user',
        ),
        migrations.AddField(
            model_name='cartaodecredito',
            name='familia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.familia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='familia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.familia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoriareceita',
            name='familia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.familia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conta',
            name='familia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.familia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metafinanceira',
            name='familia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.familia'),
            preserve_default=False,
        ),
    ]
