# Generated by Django 5.2.6 on 2025-09-23 12:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_cartaodecredito_user_remove_categoria_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='codigo_convite',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
