# Generated by Django 5.2.6 on 2025-09-23 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_familia_codigo_convite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Tesouro Selic 2029, Ações WEG, FII MXRF11', max_length=100)),
                ('tipo', models.CharField(choices=[('RF', 'Renda Fixa'), ('RV', 'Renda Variável')], max_length=2)),
                ('valor_atual', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor de mercado atual de todo o montante investido.', max_digits=15)),
                ('taxa_rendimento_anual', models.DecimalField(decimal_places=2, help_text='Para Renda Fixa, a taxa contratada. Para Renda Variável, uma estimativa.', max_digits=5)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.familia')),
            ],
        ),
        migrations.CreateModel(
            name='AporteInvestimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('conta_origem', models.ForeignKey(help_text='Conta da qual o dinheiro saiu para o aporte.', on_delete=django.db.models.deletion.PROTECT, to='core.conta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('investimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportes', to='core.investimento')),
            ],
        ),
    ]
