# Generated by Django 5.2.6 on 2025-09-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_investimento_aporteinvestimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='fatura_paga',
            field=models.BooleanField(default=False, help_text='Indica se a despesa de cartão já foi paga na fatura'),
        ),
    ]
