# Generated by Django 5.2.6 on 2025-09-24 00:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_despesa_fatura_paga'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimento',
            name='data_criacao',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
