# Generated by Django 5.2.6 on 2025-09-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_investimento_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='orcamento_mensal',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Defina um limite de gastos mensal para esta categoria.', max_digits=10),
        ),
    ]
