# Generated by Django 5.2.6 on 2025-09-24 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_categoria_orcamento_mensal'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='categoria_mae',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='core.categoria', verbose_name='Categoria Principal'),
        ),
    ]
