# Generated by Django 5.2.6 on 2025-09-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_categoria_categoria_mae'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='primeiro_acesso_concluido',
            field=models.BooleanField(default=False),
        ),
    ]
