# Generated by Django 5.2.6 on 2025-09-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_perfil_primeiro_acesso_concluido'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='etapa_onboarding',
            field=models.IntegerField(default=1, help_text='Controla a etapa do tutorial de primeiros passos.'),
        ),
    ]
