# Generated by Django 5.2.6 on 2025-09-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_perfil_etapa_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='macro_categoria',
            field=models.CharField(choices=[('NE', 'Necessidade'), ('DE', 'Desejo Pessoal'), ('ME', 'Meta Financeira'), ('NC', 'Não Classificado')], default='NC', max_length=2),
        ),
    ]
