# Generated by Django 5.2.6 on 2025-09-26 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_categoria_macro_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('preco_mensal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stripe_price_id', models.CharField(blank=True, help_text='ID do Preço no gateway de pagamento (Stripe)', max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='perfil',
            name='etapa_onboarding',
            field=models.IntegerField(default=1, help_text='Controla a etapa do tutorial.'),
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('cancelada', 'Cancelada'), ('inadimplente', 'Inadimplente'), ('incompleta', 'Incompleta')], default='incompleta', max_length=20)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True)),
                ('data_fim_periodo_atual', models.DateTimeField(blank=True, null=True)),
                ('familia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='core.familia')),
                ('plano', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.plano')),
            ],
        ),
    ]
